defmodule DcaPhx.Account.Role do
  @moduledoc """
  Domain entity representing a role.
  """
  use Ash.Resource, domain: DcaPhx.Account, data_layer: Ash.DataLayer.Ets

  # postgres do
  #   table "roles"
  #   repo(DcaPhx.Repo)
  # end

  actions do
    # Use the default implementation of the :read action
    defaults [:read, :create, :update, :destroy]

    default_accept [:name, :description]
  end

  attributes do
    # Add an autogenerated UUIDv7 primary key called :id
    uuid_v7_primary_key :id

    attribute :name, :string do
      allow_nil? false
      public? true
    end

    attribute :description, :string do
      public? true
    end
  end
end
